AWSTemplateFormatVersion: '2010-09-09'
Description: network for attendance application

Parameters:
  ProjectName:
    Description: project name
    Type: String
    Default: Attendance
  ContainerImage:
    Description: container image
    Type: String
    Default: 146114061358.dkr.ecr.ap-northeast-1.amazonaws.com/attendance:latest

Resources:
  # ECSタスク定義
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: apis
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Cpu: 4096 # 2vCPU * 2
      Memory: 8192 # 4GB * 2
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue ECSTaskExecutionRole
      ContainerDefinitions:
        - Name: !Ref ProjectName
          Image: !Ref ContainerImage
          Cpu: 2048 # 2vCPU
          Memory: 4096 # 4GB
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
  
  # ECSサービス
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${ProjectName}-Service'
      Cluster: !ImportValue AttendanceECSCluster
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      DesiredCount: 2
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !ImportValue AttendancePublicSubnet1
            - !ImportValue AttendancePublicSubnet2
          SecurityGroups:
            - !ImportValue ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: !Ref ProjectName
          ContainerPort: 8080
          TargetGroupArn: !ImportValue AttendanceTargetGroup