version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo 'pre build'
      - ls
      - aws --version
  build:
    commands:
      - echo '---------- ビルド開始 ----------'

      - echo '---------- 依存パッケージのインストール(layer) ----------'
      - cd src/layer/APISharedLayer/nodejs
      - npm ci

      - echo '---------- 依存パッケージのインストール(プロジェクト全体) ----------'
      - cd ${CODEBUILD_SRC_DIR}
      - npm ci

      # ---------- ESLint ----------'
      - npm run lint

      # ---------- 単体テストの実行 ----------'
      - npm run test

      - echo '---------- template.output.yamlファイルの出力 ----------'
      # aws cloudformation package --template-file template.yaml --output-template-file template-output.yaml --s3-bucket ${DeployBucket}
      - npm run compile
      - npm run deploy:$Env

artifacts:
  type: zip
  files:
    - template-output.yaml
    - template-parameter-$Env.json
